#!/bin/bash

if [[ ${AUDIO_CONTROL_SINK_AVAILABILITY_OVERSIZED:-0} == 1 ]]; then
  printf '%01048577d' 0
  exit 0
fi

printf '%s' "${AUDIO_CONTROL_SINK_AVAILABILITY_RESPONSE:-physical-speakers	1}"
exit "${AUDIO_CONTROL_SINK_AVAILABILITY_EXIT:-0}"
