#!/bin/bash

if [[ $* == "-f json list sinks" && -n ${AUDIO_CONTROL_DIAGNOSTIC_SINK_FIXTURE:-} ]]; then
  command cat "$AUDIO_CONTROL_DIAGNOSTIC_SINK_FIXTURE"
  exit 0
fi

echo "Unexpected pactl call: $*" >&2
exit 1
